from __future__ import annotations

import json
import os
from urllib.error import HTTPError, URLError
from urllib.request import Request, urlopen

from .models import ScoredJob


def build_discord_message(
    reviewed_count: int,
    top_jobs: list[ScoredJob],
    urgent_jobs: list[ScoredJob],
) -> str:
    lines: list[str] = []

    if urgent_jobs:
        lines.extend(["## 🚨 Urgent Internship Match Found", ""])
        for item in urgent_jobs[:5]:
            score = item.score
            lines.extend(
                [
                    f"**🚨 [{item.job.title}]({item.job.url})**",
                    f"{item.job.company} • {item.job.location}",
                    (
                        f"Skill {score.skill_fit:.1f} | "
                        f"Learning {score.learning_value:.1f} | "
                        f"Accessibility {score.accessibility:.1f}"
                    ),
                    f"Competitiveness: {score.competitiveness}",
                    (
                        "Why it fits Bobby's math + ML background: "
                        f"{score.why_match[0]}."
                    ),
                    "",
                ]
            )

    lines.extend(
        [
            "## Internship Intelligence Report",
            f"Jobs reviewed: **{reviewed_count}**",
            f"Top matches: **{len(top_jobs)}**",
            f"Urgent matches: **{len(urgent_jobs)}**",
            "",
            "**Top Opportunities**",
        ]
    )
    for index, item in enumerate(top_jobs, start=1):
        score = item.score
        lines.extend(
            [
                (
                    f"{index}. [{item.job.title}]({item.job.url}) — "
                    f"{item.job.company}, {item.job.location} — "
                    f"**{score.overall:.2f}/10**"
                )
            ]
        )

    footer = "Generated by Bobby’s Internship Intelligence Agent"
    message = "\n".join([*lines, "", footer])
    if len(message) > 2000:
        available = 2000 - len(footer) - 6
        message = f"{message[:available].rsplit(chr(10), 1)[0]}\n...\n{footer}"
    return message


def send_discord_webhook(message: str) -> bool:
    url = os.getenv("DISCORD_WEBHOOK_URL")
    if not url:
        return False

    request = Request(
        url,
        data=json.dumps({"content": message}).encode("utf-8"),
        method="POST",
        headers={"Content-Type": "application/json"},
    )
    try:
        with urlopen(request, timeout=15) as response:
            if 200 <= response.status < 300:
                print("Discord notification sent.")
                return True
            print(f"Discord notification failed with status {response.status}.")
    except HTTPError as exc:
        print(f"Discord notification failed with status {exc.code}.")
    except (URLError, TimeoutError) as exc:
        print(f"Discord notification failed: {type(exc).__name__}")
    return False


def send_discord_notification(
    reviewed_count: int,
    candidates: list[ScoredJob],
    urgent_threshold: float,
) -> bool:
    """Send the ranked daily summary when the report has relevant jobs."""
    urgent_jobs = [
        item for item in candidates if item.score.overall >= urgent_threshold
    ]
    if not candidates:
        return False

    ranked = sorted(
        candidates,
        key=lambda item: item.score.overall,
        reverse=True,
    )
    top_jobs = ranked[:5]
    urgent_jobs = sorted(
        urgent_jobs,
        key=lambda item: item.score.overall,
        reverse=True,
    )

    message = build_discord_message(reviewed_count, top_jobs, urgent_jobs)
    return send_discord_webhook(message)
